version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metrobus_cdmx
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runscript insert_data &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/geomelt_app
    ports:
      - '8000:8000'
    depends_on:
      - db