# Generated by Django 3.2 on 2022-06-24 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alcaldias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrobus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('townhall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrobuses', to='alcaldias.townhall')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
