# Generated by Django 4.0.3 on 2022-03-02 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcaldias', '0001_initial'),
        ('metrobuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrobus',
            name='alcaldia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alcaldias.alcaldia'),
        ),
        migrations.AlterField(
            model_name='metrobus',
            name='altitud',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='metrobus',
            name='longitud',
            field=models.FloatField(default=0),
        ),
    ]
