# Generated by Django 4.0.3 on 2022-03-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrobuses', '0002_alter_metrobus_alcaldia_alter_metrobus_altitud_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metrobus',
            old_name='metro_id',
            new_name='metrobus_id',
        ),
    ]
